"use client";
import { Rubik } from "next/font/google";
import "./globals.css";
// import { makeServer } from "./fake-db/mirage";
import { Provider } from "react-redux";
import { store } from "./redux/store";

const rubik = Rubik({ subsets: ["latin"], weight: ["400", "500", "700"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// ** mock server
// if (process.env.NODE_ENV === "development") {
//   makeServer({ environment: "development" });
// }
// if (process.env.NODE_ENV === "production") {
//   makeServer({ environment: "production" });
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body className={`${rubik.className} text-base bg-white-lilac`}>
          {children}
        </body>
      </Provider>
    </html>
  );
}
